import './js/load-genres';
import './js/totop';
import './js/header';
import './js/libhero';
import './js/liblist';
import './js/modal-poster';
import './js/modal-trailer';
import './js/ourteam';
import './js/footer';
